module OceanStateEstimation

pkg_pth=dirname(pathof(OceanStateEstimation))

include("downloads.jl")
include("ECCO.jl")

get_ecco_files=downloads.get_ecco_files
dataverse_lists=downloads.dataverse_lists
get_from_dataverse=downloads.get_from_dataverse
get_ecco_variable_if_needed=downloads.get_ecco_variable_if_needed
get_ecco_velocity_if_needed=downloads.get_ecco_velocity_if_needed
get_occa_variable_if_needed=downloads.get_occa_variable_if_needed
get_occa_velocity_if_needed=downloads.get_occa_velocity_if_needed

MITPROFclim_download=downloads.MITPROFclim_download
CBIOMESclim_download=downloads.CBIOMESclim_download
ECCOdiags_add=downloads.ECCOdiags_add

export dataverse_lists, get_from_dataverse, ECCOdiags_add
export get_ecco_variable_if_needed, get_ecco_velocity_if_needed
export get_occa_variable_if_needed, get_occa_velocity_if_needed

export ECCO, ECCO_helpers, ECCO_io, ECCO_diagnostics
export ScratchSpaces

end # module
